import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const pretendard = localFont({
    src: [
        { path: '../fonts/Pretendard-Regular.woff2', weight: '400' },
        { path: '../fonts/Pretendard-Medium.woff2',  weight: '500' },
        { path: '../fonts/Pretendard-SemiBold.woff2', weight: '600' },
        { path: '../fonts/Pretendard-Bold.woff2',    weight: '700' },
        { path: '../fonts/Pretendard-ExtraBold.woff2', weight: '800' },
    ],
    variable: '--font-pretendard',
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Hyun | Frontend Developer',
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${pretendard.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
